name: Build tests

on:
  release:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build_release:
        description: 'Build Release binaries'
        required: false
        type: boolean

# Set the build type here
env:
  B_BUILD_TYPE: ${{ (inputs.build_release || github.event_name == 'release') && 'Release' || 'Debug' }}

jobs:
  mac-build:
    name: ${{ matrix.name}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       include:
         - name: macOS-Apple_Silicon
           os: macos-14
           qt-version: 6.6
           min-macOS-version: 14
           arch: 'arm64'

    env:
      VERBOSE: 1
      TERM: xterm-256color
      OpenSSL_Install_Path: "/Users/runner/openssl"
      OpenSSL_Version: 3.2.0

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{matrix.qt-version}}
          modules: ${{matrix.qt-modules}}
          cache: true
          cache-key-prefix: macOS-${{matrix.os}}-Qt${{matrix.qt-version}}

      - name: Setup the image
        run: |
          brew install ninja

      - name: Cache OpenSSL Universal
        id: cache-openssl
        if: matrix.os == 'macos-14'
        uses: actions/cache@v4.2.4
        with:
          path: ${{env.OpenSSL_Install_Path}}
          key: macOS-${{matrix.os}}-ssl-${{matrix.arch}}-${{env.OpenSSL_Version}}

      - name: Build OpenSSL Universal
        if: ((steps.cache-openssl.outputs.cache-hit != 'true') && (matrix.os == 'macos-14'))
        run: |
          wget https://github.com/openssl/openssl/releases/download/openssl-${{env.OpenSSL_Version}}/openssl-${{env.OpenSSL_Version}}.tar.gz
          tar -xf openssl-${{env.OpenSSL_Version}}.tar.gz
          echo "#!/bin/bash
          if [[ \$* == *-arch\ x86_64* ]] && ! [[ \$* == *-arch\ arm64* ]]; then
            cc -arch arm64 \$@
          else
            cc \$@
          fi" >> /Users/runner/cc_override
          chmod a+x /Users/runner/cc_override
          cat /Users/runner/cc_override
          export MACOSX_DEPLOYMENT_TARGET=${{matrix.min-macOS-version}}
          export CC=/Users/runner/cc_override
          cd openssl-${{env.OpenSSL_Version}}
          ./configure no-asm darwin64-x86_64-cc --prefix=${{env.OpenSSL_Install_Path}}
          make
          make install

      - uses: actions/checkout@v4
        with:
          path: input-leap
          submodules: recursive

      - name: Setup the build
        run: |
          cmake -DCMAKE_BUILD_TYPE="${B_BUILD_TYPE}" -S input-leap -B build -G Ninja \
                -DCMAKE_UNITY_BUILD=1 \
                -DOpenSSL_ROOT=${{env.OpenSSL_Install_Path}} \
                -DCMAKE_OSX_SYSROOT=$(xcode-select --print-path)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=${{matrix.min-macOS-version}} -DCMAKE_UNITY_BUILD=1 \
                -DQT_DEFAULT_MAJOR_VERSION=$(echo ${{matrix.qt-version}} | cut -c -1) \
                -DINPUTLEAP_VERSION_DESC=${{ (env.B_BUILD_TYPE == 'Release') && 'release' || 'git' }} \
                -DINPUTLEAP_BUILD_GULRAK_FILESYSTEM=${{ matrix.qt-version == '5.15' && '1' || '0' }} \
                -DCMAKE_OSX_ARCHITECTURES="${{matrix.arch}}"

      - name: Run the build
        run: |
          cmake --build build --parallel

      - uses: actions/upload-artifact@v4
        if: env.B_BUILD_TYPE == 'Release'
        with:
          name: ${{ matrix.name }}-installer
          path: ./build/bundle/*.dmg
          if-no-files-found: error

      - name: Archive debug app
        if: env.B_BUILD_TYPE != 'Release'
        run: tar -czf InputLeap-${{matrix.name}}.tar.gz -C build/bundle InputLeap.app

      - uses: actions/upload-artifact@v4
        if: env.B_BUILD_TYPE != 'Release'
        with:
          name: ${{ matrix.name }}-debug
          path: ./InputLeap*.tar.gz
          if-no-files-found: error

  win-build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
       include:
         - name: Windows Qt5
           os: windows-2022
           qt-version: 5.15
           qt-major: 5

    steps:
      - uses: actions/checkout@v4
        with:
          path: input-leap
          submodules: recursive

      - name: Download Bonjour SDK-like
        id: bonjour
        run: |
          $ErrorActionPreference = "Stop"
          New-Item -Force -ItemType Directory -Path .\deps

          Invoke-WebRequest 'https://github.com/nelsonjchen/mDNSResponder/releases/download/v2019.05.08.1/x64_RelWithDebInfo.zip' -OutFile 'deps\BonjourSDKLike.zip' ;
          Expand-Archive .\deps\BonjourSDKLike.zip -DestinationPath .\deps\BonjourSDKLike
          Remove-Item deps\BonjourSDKLike.zip

          "path=$env:GITHUB_WORKSPACE\deps\BonjourSDKLike" >> $env:GITHUB_OUTPUT

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{matrix.qt-version}}
          modules: ${{matrix.qt-modules}}
          cache: true
          cache-key-prefix: windows-${{matrix.os}}-Qt${{matrix.qt-version}}

      - name: Configure build system
        run: |
          New-Item -Force -ItemType Directory -Path .\build | Out-Null

          cd build

          cmake -S ..\input-leap -G "$env:CMAKE_GEN" -A x64 -D CMAKE_BUILD_TYPE=$B_BUILD_TYPE `
            -DQT_DEFAULT_MAJOR_VERSION=${{matrix.qt-major}} `
            -DINPUTLEAP_VERSION_DESC=${{ (env.B_BUILD_TYPE == 'Release') && 'release' || 'git' }} `
            -DINPUTLEAP_BUILD_GULRAK_FILESYSTEM=${{ matrix.qt-major == '5' && '1' || '0' }} `
            -DDNSSD_LIB="$env:BONJOUR_SDK_HOME\Lib\x64\dnssd.lib" -D CMAKE_INSTALL_PREFIX=input-leap-install
        env:
          VS_PATH: ${{ matrix.os == 'windows-2019' && '%ProgramFiles(x86)%\Microsoft Visual Studio\2019' || '%ProgramFiles%\Microsoft Visual Studio\2022' }}
          CMAKE_GEN: ${{ matrix.os == 'windows-2019' && 'Visual Studio 16 2019' || 'Visual Studio 17 2022' }}
          BONJOUR_SDK_HOME: ${{ steps.bonjour.outputs.path }}

      - name: Run build system
        run: |
          cmake --build build --config $env:B_BUILD_TYPE --target install

      - name: Create Archive
        run: Compress-Archive -Path build\input-leap-install\* -DestinationPath ${{ env.B_BUILD_TYPE }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-${{ env.B_BUILD_TYPE }}
          path: ${{ env.B_BUILD_TYPE }}.zip
          if-no-files-found: warn

      - name: Build the Installer
        if: env.B_BUILD_TYPE == 'Release'
        run: |
          & "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" /Qp .\build\installer-inno\input-leap.iss

      - uses: actions/upload-artifact@v4
        if: env.B_BUILD_TYPE == 'Release'
        with:
          name: windows-installer-${{ matrix.name }}
          path: .\build\installer-inno\bin
          if-no-files-found: error
